#!/usr/bin/python

import sys


crackStr = sys.argv[1].decode("hex")
splitChar = 0
winnerString = []

while splitChar < 128:
	splitArr = []
	scoreVal = 0
	for crack in crackStr:
		newchar = ord(crack)^splitChar
		if newchar == 32 or (newchar > 64 and newchar < 91) or (newchar > 96 and newchar < 123):
			scoreVal = scoreVal + 1
		splitArr.append(chr(newchar))
	if scoreVal >= len(crackStr)-1:  #magic numbers, oh joy...
		splitArr.append(" || ")
		splitArr.append(chr(splitChar))
		winnerString.append(''.join(splitArr))
	
	splitChar = splitChar + 1

print winnerString
